'use server';

/**
 * @fileOverview AI flow to generate a personalized message when a countdown ends, referencing either anniversary or birthday.
 *
 * - generatePersonalizedMessage - A function that generates a personalized message based on the event type.
 * - GeneratePersonalizedMessageInput - The input type for the generatePersonalizedMessage function.
 * - GeneratePersonalizedMessageOutput - The return type for the generatePersonalizedMessage function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GeneratePersonalizedMessageInputSchema = z.object({
  eventTag: z
    .string()
    .describe("The tag associated with the event, e.g., 'Anniversary' or 'Birthday'."),
  date: z.string().describe('The date of the event (e.g., 2022-02-05).'),
});
export type GeneratePersonalizedMessageInput = z.infer<typeof GeneratePersonalizedMessageInputSchema>;

const GeneratePersonalizedMessageOutputSchema = z.object({
  message: z.string().describe('The personalized message generated by the AI.'),
});
export type GeneratePersonalizedMessageOutput = z.infer<typeof GeneratePersonalizedMessageOutputSchema>;

export async function generatePersonalizedMessage(
  input: GeneratePersonalizedMessageInput
): Promise<GeneratePersonalizedMessageOutput> {
  return generatePersonalizedMessageFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generatePersonalizedMessagePrompt',
  input: {schema: GeneratePersonalizedMessageInputSchema},
  output: {schema: GeneratePersonalizedMessageOutputSchema},
  prompt: `You are a personalized message generator for special romantic events.

  Based on the event tag, generate a heartfelt message.
  If the event tag is 'Anniversary', create a message celebrating the anniversary on {{{date}}}.
  If the event tag is 'Birthday', create a message celebrating the birthday on {{{date}}}.
  Otherwise, create a general romantic message for an unspecified special day on {{{date}}}.
  Make the message approximately 2-3 sentences long.
  `,
});

const generatePersonalizedMessageFlow = ai.defineFlow(
  {
    name: 'generatePersonalizedMessageFlow',
    inputSchema: GeneratePersonalizedMessageInputSchema,
    outputSchema: GeneratePersonalizedMessageOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
